### ISSUE TITLE
Error with inputs and includes

### ISSUE THREAD

**Issue by PierreMarchand20** [sylvainhalle/textidote#81] opened 2019-04-12 11:40 UTC
I noticed that textidote does not find subfiles with `\input` if the name of the file does not contain `.tex`. But it should since LaTex works either way.

Even worse, using `\include` with `.tex` at the end of the filename does not work in LaTeX but it seems necessary for textidote to find the subfiles

**Comment by ngartner** [comment] 2019-05-23 12:21
Hello, in addition it seems TeXtidote can't find items in subfolders. For exemple if the Path given is .\Part1\Part1.tex it returns "not found".

**Comment by sylvainhalle** [comment] 2019-08-05 14:22
The last comment is related to #64

**Comment by PierreMarchand20** [comment] 2019-08-05 21:59
I still have an issue:
```
thesis.tex
corps/bem_chap.tex
corps/bem/sobolev_spaces.tex
```
with `\include{corps/bem_chap}` in `thesis.tex` and `\input{corps/bem/sobolev_spaces}` in `corps/bem_chap.tex`
and I get (for example)
```
File corps/corps/bem/sobolev_spaces.tex not found (skipping)
```

**Comment by PierreMarchand20** [comment] 2019-08-05 22:12
Notice that I also have the issue with I use `\input` with the file extension.

**Comment by sylvainhalle** [comment] 2019-08-06 00:08
Ah, I think I see. Is the `input` path relative to the root file, or relative to the file that contains the command? TeXtidote interprets it as the latter.

**Comment by PierreMarchand20** [comment] 2019-08-06 08:46
It is relative to the root file, it does not work otherwise.

**Comment by sylvainhalle** [comment] 2019-08-06 12:40
OK, so this is why it doesn't work. I'll fix this shortly.

**Comment by sylvainhalle** [comment] 2019-08-06 14:32
I've just pushed a fix. Could someone please check that it has the intended behavior (I checked on my side and it seems to be OK). Then I'll re-re-close the issue.

**Comment by PierreMarchand20** [comment] 2019-08-06 14:36
How can I try it ? I am on macOS so I need the `.jar` file I think

**Comment by sylvainhalle** [comment] 2019-08-06 15:11
Here is a Dropbox link to a compiled JAR: https://www.dropbox.com/s/amgcn61dwvzpnk2/textidote.jar?dl=0

**Comment by PierreMarchand20** [comment] 2019-08-06 15:44
It works fine on my phd thesis 👍

**Comment by PierreMarchand20** [comment] 2019-08-06 16:06
Actually there is something. The last update fixed the case where someone call textidote on the main file. The issue is that the file may be too big to read so that he wants to call textidote on a subfile using the option `--read-all`. In this case it does not work.

**Comment by PierreMarchand20** [comment] 2019-08-06 16:11
One thing that could help is that in multi-file project, usually we use magic comment such as `% !TEX root = ../thesis.tex` to refer to the main file of the project. 

So that you could use it to fix the paths

**Comment by PierreMarchand20** [comment] 2019-08-14 16:46
Magic comments such as `!TEX root` are quite standard for multi-file project 
- https://www.texdev.net/2011/03/24/texworks-magic-comments/
- https://tex.stackexchange.com/a/84687/98084
- https://github.com/TeXworks/texworks/wiki/Magic-Comments

**Comment by domoritz** [comment] 2019-08-14 16:53
I just wanted to note that the 0.8 release fixed issues I experienced with includes before. Thank you @sylvainhalle!

**Comment by hassec** [comment] 2019-08-19 14:19
I've actually noticed some weird behavior as far as includes go.

My folder structure is a main.tex file with multiple `input{content/xyz.tex}` statements.    
When running a check, a get a nice HTML report that lists all of these files.
However, running `textidote --clean` to check the cleaned version I only see the output of the main file... 

Am I missing something, or is the `clean` option not including these files correctly?

**Comment by sylvainhalle** [comment] 2019-08-20 22:58
@hassec: this is a bug; the `--clean` option should work recursively on included files.

**Comment by sylvainhalle** [comment] 2019-08-20 23:03
@PierreMarchand20: I'd prefer a command line switch you could pass to TeXtidote. I am a bit afraid if I need to start supporting the features of _another_ software. And as I can see, there are lots of other magic commands, so once you start supporting one, somebody else will ask for another...

**Comment by PierreMarchand20** [comment] 2019-08-21 06:50
My point was that actually it is not specific to a software. It is a convention widely used in my opinion, it worked like that in _all_ the “softwares”/plugins of editor I used so far (texstudio, texshop, Plugins for atom and now VSCode). Actually in the second answer of https://tex.stackexchange.com/questions/78101/when-and-why-should-i-use-tex-ts-program-and-tex-encoding you can see that all the presented softwares support magic comment for root.


Besides, magic comments give information to the compiler, so that the other magic comments should not be relevant for TeXidote. (See first answer of https://tex.stackexchange.com/questions/78101/when-and-why-should-i-use-tex-ts-program-and-tex-encoding for most of the magic comments)

That being said, a command line like `-root rootfile` should also work well.

**Comment by samuelstjean** [comment] 2019-09-24 14:20
I'm wondering, does it also work when using subfiles? Seems like it picks up all of my include/input, but not my files included from the subfile package, which allows to specify a sub document with it's begin/end clauses and everything, kind of like this 

~~~latex
\chapter{Introduction}
\label{chap:introduction}
 
\begin{filecontents}{bibfiles/intro.bib}
@online{wiki_neuron,
author = "BruceBlaus",
title = "Neuron",
year = "2019",
% urlseen = "03-02-13",
url = "https://commons.wikimedia.org/wiki/File:Blausen_0657_MultipolarNeuron.png",
keywords = {wiki},
note = "https://creativecommons.org/licenses/by-sa/3.0/legalcode",
}
\end{filecontents}
 
 
\begin{refsection}
\subfile{chapters/intro/intro.tex}
\pageclear
\printbibliography
\end{refsection}
 
\begin{refsection}[bibfiles/intro.bib]
\nocite{*}
\printbibliography[title={Additional attributions},heading=subbibliography]
\pageclear
\end{refsection}
~~~

Here my file intro.tex is pretty much a standalone document, so it may just be a case of allowing these files in addition to the input/include command. Perfect when you are lazy and just adding in entirely the content of an old document you did previously.

**Comment by sylvainhalle** [comment] 2019-09-25 11:15
Currently it only works for `\input` and `\include`. Do you think it would just be a matter of adding the `\subfile` to the detection? In other words, do these files need different handling from `\input` and `\include`?

**Comment by samuelstjean** [comment] 2019-09-25 13:14
It depends if you also look explicitly for \begin and \end document. A subfile will always be of class subfiles and refers to the file calling it, just like this

~~~latex
\documentclass[../intro.tex]{subfiles}
\begin{document}

stuff here

\end{document}
~~~

The main use is to have very large documents which are self contained, like chapters in a thesis that are built using your old manuscripts. In my previous snippet, the subfile part refers to this file here, that is 

\subfile{chapters/intro/intro.tex} is part of my main document using include and intro.tex (in a barebone version) is what I posted here. If it's not super clear, the package documention is about 5 pages long https://ctan.org/pkg/subfiles

**Comment by sylvainhalle** [comment] 2019-09-26 01:21
OK, will mark it as enhancement, but I'll have to look at the doc in detail to make sure it is not a case of #56.

**Comment by sylvainhalle** [comment] 2020-06-19 00:50
May I suggest we move this discussion to #131

**Closed by sylvainhalle** 2020-06-19 00:50 UTC
Labels: bug
