### ISSUE TITLE
Simple tips could be ignored

### ISSUE THREAD

**Issue by JorricksTU** [sylvainhalle/textidote#20] opened 2018-07-05 11:58 UTC
Hello,

I'm writing a report in a certain research field where the term intersection is more accepted than crossroads. However, the spellings check says that all words which contain 'intersection' should be changed to some form of crossroad.

This is not my intention and hence I have 100 times the same notice in the html report.  
Could there maybe be a function to disable this message? 
Maybe also by adding this to the dictionary?

**Comment by JorricksTU** [comment] 2018-07-05 14:39
Hello,

What would the command look like in that case?

**Comment by sylvainhalle** [comment] 2018-07-05 23:13
You'd write something like this:
```
java -jar textidote.jar --check en --dict dictionary.txt myfile.tex
```
The file `dictionary.txt` would contain a list of words to be ignored, each on a separate line.

**Comment by sylvainhalle** [comment] 2018-07-05 23:14
Sorry, wrong button

**Comment by JorricksTU** [comment] 2018-07-06 10:22
Oh sorry I wasn't clear on the command. I already tried that before posting for the html and just the command line version. Neither respond to the dictionary.

**Comment by sylvainhalle** [comment] 2018-07-06 22:23
I think that if issue #4 is addressed, it will solve this one at the same time (you'll be able to disable that specific rule by giving its ID). So I'll close this one as a duplicate of #4.

**Closed by sylvainhalle** 2018-07-06 22:23 UTC
Labels: duplicate
