### ISSUE TITLE
language model not working

### ISSUE THREAD

**Issue by MatisPatel** [sylvainhalle/textidote#114] opened 2019-12-13 15:12 UTC
Installed using deb package.
Downloaded languagemodel from site and put the en folder in home. 

run command
```
textidote --read-all --remove-macros citep --output html --check en_UK --languagemodel ~/ Chapter06.tex > spellchecks/discussion_check.html
```
get error
> Could not load codec 'Lucene410'.  Did you forget to add lucene-backward-codecs.jar? N-gram rules will be ignored.

**Comment by sylvainhalle** [comment] 2019-12-13 15:37
Duplicate of #104

**Closed by sylvainhalle** 2019-12-13 15:37 UTC
