### ISSUE TITLE
Issues with German text (Umlaute)

### ISSUE THREAD

**Issue by freakyuser-osm** [sylvainhalle/textidote#99] opened 2019-08-08 14:17 UTC
I'm running the tool on my German (UTF-8) Text with --check de and save it to an html file.

Unfortunately, it seems like the special German characters (äöüß) aren't processed correctly. They're printed as questionmarks in the html output.

It throws the following warning
`Warning: At the moment, your platform (Windows) is not supported by the official XGBoost maven package; ML-based suggestion reordering is disabled.`

Example:
```
\documentclass[]{scrbook}
\begin{document}
\chapter{Einleitung}

Dies ist ein erster Testsatz. Anschließend folgt ein zweiter mit Übereinstimmung.

\end{document}
```

**Comment by freakyuser-osm** [comment] 2019-08-09 18:13
As a follow up: I tested it on Ubuntu, where it works like a charm! So it seems like it isn't a general issue...

**Comment by sylvainhalle** [comment] 2019-08-12 19:41
Thanks for your input. A few questions to clarify the situation:

1. What is the browser you use (in both cases)?
2. Is the warning you mention thrown by TeXtidote or by the browser?

**Comment by freakyuser-osm** [comment] 2019-08-12 21:00
Thanks for your reply!

1. I'm using Firefox on Windows and Ubuntu
2. The warning was thrown by TeXtidote

In general, the problem is solved for me, I'm fine with using my Linux machine for the spell check. But I'm happy to provide you with more information, in case you intend to dig deeper into it :)

Btw, thank you very much for your amazing tool! It's much more convenient than the other solutions for using languagetool on tex files (including TeXstudio)!

**Comment by sylvainhalle** [comment] 2019-08-13 12:57
The warning is a LT issue; I can't do much for this. Seems related to this: https://github.com/languagetool-org/languagetool/issues/1813

Proposed fix: https://github.com/fabrichter/languagetool/commit/c326e3f04fc94c22ebd88fbf26cc2beb32262f4f

Looks like some feature is not supported on Windows, and the message is printed directly on stdout instead of going through a normal logging statement. I'd mark this part of the issue as `wontfix`.

However, the special characters in the HTML output seem to be a different problem altogether. I'll keep investigating.

**Comment by freakyuser-osm** [comment] 2019-08-13 13:20
Here is a the output I mentioned:
[test.zip](https://github.com/sylvainhalle/textidote/files/3497068/test.zip)

Please note, that the text appears correct in the output, but languagetool seems to receive "wrong" text.

Additionially, if I run it against my real document, I've seen, that the Text is sometimes displayed correctly and sometimes wrong. Although even the correctly displayed text seems to be passed to languagetool the wrong way, and thus marked as a spelling error:

![Real_Document](https://user-images.githubusercontent.com/23432012/62944401-e1c8d180-bddc-11e9-8ddf-b041dda0bd2c.png)

**Comment by sylvainhalle** [comment] 2020-05-15 13:37
I just ran TeXtidote on my machine with the files provided. I cannot reproduce the problem: I get no spelling error and all the characters display correctly.

**Closed** 2020-05-15 13:52 UTC
Labels: bug

**Comment by JapuDCret** [comment] 2020-12-01 15:11
I managed to fix this issue myself, while retaining UTF-8 in a windows environment:
`java -Dfile.encoding=UTF-8 -jar textidote.jar --check de --encoding utf-8 --output html main.tex > report.html`
