### ISSUE TITLE
Option --clean not working for sub-files

### ISSUE THREAD

**Issue by wenlzhang** [sylvainhalle/textidote#149] opened 2020-09-28 19:42 UTC
The option `--clean` does not work for me when there are files that are included in sub-folders like this `\input{folder/file.tex}`. Specifically, all `.tex` files in sub-folders are ignored, and only the main `.tex` file was checked. Without this option, however, it works like a charm.

**Comment by sylvainhalle** [comment] 2020-09-30 12:22
Duplicate of #132

**Closed by sylvainhalle** 2020-09-30 12:22 UTC
Labels: duplicate
