### ISSUE TITLE
Have an easy to parse command line output

### ISSUE THREAD

**Issue by fikovnik** [sylvainhalle/textidote#88] opened 2019-07-24 15:17 UTC
Textidote is a perfect match for a checker for emacs's [flycheck](https://www.flycheck.org/en/latest/) which can check tex document on the fly. I managed to integrate it, but it requires a [wrapper](https://github.com/fikovnik/dotfiles/blob/master/.emacs.d/config.org#create-a-wrapper) (a shell script that tries to consolidate the output) making it difficult to create a PR to flycheck. Would it be possible to have one more renderer which is just plain simple?

Instead of:
```
* L1092C17-L1092C26 Do not refer to sections using hard-coded numbers. Use
  \ref instead. [sh:hcsec]
  confusion~\cite[Section 10.2,][]{Suereth2012}. As
                  ^^^^^^^^^^
* L1100C13-L1100C22 Do not refer to sections using hard-coded numbers. Use
  \ref instead. [sh:hcsec]
  apply~\cite[Section 4.2,][]{odersky2017}.
              ^^^^^^^^^^
* L24C24-L24C29 Use a backslash after the second period; otherwise LaTeX will
  think it is a full stop ending a sentence. [sh:011]
  \newcommand{\Ie}{\emph{i.e.}\xspace}
```

do:
```
main.tex:1092:17:1092:26 [sh:hcsec] Do not refer to sections using hard-coded numbers. Use \ref instead.
main.tex:1100:13:1100:22 [sh:hcsec] Do not refer to sections using hard-coded numbers. Use \ref instead.
main.tex:24:24:24:29 [sh:011] Use a backslash after the second period; otherwise LaTeX will think it is a full stop ending a sentence.
```

Or something like this which is plain easy to parse using regular expressions.

**Comment by toolcreator** [comment] 2019-07-24 15:43
Hi, I've thought about something similar.
I use visual studio code to write latex, and there I need a single line of output to extract the relevant information from via regular expressions.
Currently I transform the output using a python script.
Depending on whether I have the time, I wanted to implement that in textidote and provide a pull request in the next few days.
For me something like
`main.tex(1092,17,1092,26): Do not refer to sections using hard-coded numbers. Use \ref instead. "confusion~\cite[Section 10.2,][]{Suereth2012}. As"`
worked well, but I guess we could discuss what the best option would be here.

**Comment by sylvainhalle** [comment] 2019-07-25 06:50
Please have a look at issue #60. If you'd like to contribute, I'd strongly encourage you to write something that outputs to the format mentioned in this issue.

Duplicate of #60

**Comment by toolcreator** [comment] 2019-07-25 07:45
Thanks for the reply, though I would argue that this is not a duplicate.
According to the [LanguageTool command-line options documentation](http://wiki.languagetool.org/command-line-options), the suggested XML output is marked as deprecated, and JSON is encouraged.
 I can see the benefit of JSON output for compatibility with other tools, but this is not the same as having a simple, single line of output per error, parseable by regular expressions.
It would probably be possible to print the JSON in such a way, but this does not sound like the cleanest solution to me.
Of course it also wouldn't be nice to clutter the command line interface with different output formats, so maybe it would be a good idea to have a single argument `--output` with multiple options such as `plain [default], html, singleline, json` or something similar.

**Comment by sylvainhalle** [comment] 2019-07-26 07:18
This makes sense, I'll reopen the issue. Creating the output you describe requires a simple re-arrangement of the console output. Should be easy to add for the next release.

**Closed** 2019-08-02 16:07 UTC
